"""added unique constraints to votes  table

Revision ID: e6c583b25833
Revises: 48453960d54f
Create Date: 2026-07-15 00:22:21.307638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c583b25833'
down_revision: Union[str, Sequence[str], None] = '48453960d54f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_vote_once_per_position', 'votes', ['voter_id', 'position_id', 'election_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_vote_once_per_position', 'votes', type_='unique')
    # ### end Alembic commands ###
